"""add refresh token family tracking

Revision ID: a118adba2796
Revises: 78f603f1be9b
Create Date: 2026-08-21 22:08:57.966477

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a118adba2796"
down_revision: Union[str, Sequence[str], None] = "78f603f1be9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_tokens", sa.Column("family_id", sa.Uuid(), nullable=False))
    op.add_column(
        "refresh_tokens", sa.Column("replaced_by_token_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_replaced_by_token_id"),
        "refresh_tokens",
        ["replaced_by_token_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_refresh_tokens_replaced_by_token_id"), table_name="refresh_tokens"
    )
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "replaced_by_token_id")
    op.drop_column("refresh_tokens", "family_id")
    # ### end Alembic commands ###
